---
name: Label Issues
on:
  issues:
    types:
      - opened
jobs:
  label_issues_bugs:
    if: github.repository_owner == 'KelvinTegelaar' && contains(github.event.issue.title, 'Bug')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          add-labels: 'unconfirmed-by-user'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  label_issues_frs:
    if: github.repository_owner == 'KelvinTegelaar' && contains(github.event.issue.title, 'Feature')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          add-labels: 'enhancement, no-priority'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
